name: Test
on:
  - push
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11

      - name: make
        run: nix-shell --command 'make'

      - name: make test
        run: nix-shell --command 'make test'

      - name: Run executable
        run: ./hello > output.txt

      - name: Test output
        run: echo "Hello, world" | diff output.txt -

      - name: make clean
        run: nix-shell --command 'make clean'
